export const PHOTO = [
	{
		id: '758-65-4188',
		author: 'kirill_1021',
		title: 'Cat',
		description: 'Nulla totam eius rerum. Nulla totam eius rerum.',
		categories: ['cats', 'funny'],
		source: '1.jpg',
	},
	{
		id: '377-28-8205',
		author: 'jojo_master',
		title: 'Dog',
		description: 'Consequatur nihil voluptates aut. Tempore architecto omnis occaecati. Provident aut deserunt nesciunt voluptas ut ex. Est ea saepe animi blanditiis soluta nesciunt. Voluptas facere ducimus sunt ab cum placeat temporibus.',
		categories: ['dogs', 'funny'],
		source: '7.jpg',
	},
	{
		id: '597-96-3806',
		author: 'kirill_1021',
		title: 'Raccoon',
		description: 'Laborum repellendus rerum non.',
		categories: ['raccoons', 'funny'],
		source: '11.jpg',
	},
	{
		id: '466-97-3058',
		author: 'user91940913',
		title: 'Cat',
		description: 'Fuga neque vel voluptas quidem voluptatem eum. Quia iure laborum. Voluptas voluptas illum dolorum. Iste consequuntur nulla dignissimos tempora quibusdam.',
		categories: ['cats', 'funny', 'music'],
		source: '3.jpg',
	},
	{
		id: '198-47-0083',
		author: 'user91940913',
		title: 'Dog',
		description: 'Ipsam sequi commodi est ipsum dolorem doloremque. Magni voluptatem est. Temporibus nesciunt est deserunt enim culpa. Molestiae illum corrupti sunt quam optio explicabo deserunt. Adipisci voluptatum necessitatibus quis similique.',
		categories: ['dogs', 'funny'],
		source: '8.jpg',
	},
	{
		id: '396-88-7125',
		author: 'jojo_master',
		title: 'Raccoon',
		description: 'Vel quos omnis et impedit porro eveniet ut. Molestiae eos nulla doloribus. Dolorem et accusantium quisquam.',
		categories: ['raccoons', 'funny'],
		source: '12.jpg',
	},
	{
		id: '769-64-3142',
		author: 'blablabla392_2008',
		title: 'Raccoon',
		description: 'Sequi rem amet tempora. Voluptatem fuga totam beatae eos nesciunt. Iste sit eligendi ipsum voluptatem. Iusto quis assumenda debitis voluptas asperiores nulla. At libero dolorem enim voluptate illo.',
		categories: ['raccoons'],
		source: '15.jpg',
	},
	{
		id: '315-68-8459',
		author: 'user91940913',
		title: 'Raccoon',
		description: 'Et impedit sunt culpa asperiores. Nisi inventore qui qui voluptatibus. In numquam id. Possimus aut eum dolore sequi quaerat nihil.',
		categories: ['raccoons', 'funny'],
		source: '13.jpg',
	},
	{
		id: '836-72-1727',
		author: 'amogus',
		title: 'Cat',
		description: 'Ea omnis non similique. Minima sit et maiores accusantium. Ab voluptate libero sed a est dolorem pariatur.',
		categories: ['cats', 'funny'],
		source: '4.jpg',
	},
	{
		id: '780-61-8963',
		author: 'kirill_1021',
		title: 'Dog',
		description: 'Dicta minima tempora recusandae. Corrupti et nostrum ipsa est et. Aut ex et aut unde. Fuga accusantium asperiores velit. Non amet natus quam.',
		categories: ['dogs', 'funny'],
		source: '6.jpg',
	},
	{
		id: '713-91-7492',
		author: 'jojo_master',
		title: 'Cat',
		description: 'Accusantium eum occaecati qui ut eius. Ut quidem voluptas consequatur natus et. Architecto et non minima tenetur est omnis. Et maiores voluptatibus aut consequatur. Quis est pariatur aut suscipit sed distinctio.',
		categories: ['cats', 'funny'],
		source: '2.jpg',
	},
	{
		id: '815-47-6781',
		author: 'amogus',
		title: 'Dog',
		description: 'Consequatur deleniti accusamus nobis ab qui beatae occaecati.',
		categories: ['dogs', 'funny'],
		source: '9.jpg',
	},
	{
		id: '465-11-3224',
		author: 'blablabla392_2008',
		title: 'Cat',
		description: 'Omnis iusto sit eum minima dolore. Qui ad aut ut quasi. Temporibus voluptatem ut eaque maiores dolores. Repellat iste animi molestiae voluptatem. Iusto libero eos ad ex.',
		categories: ['cats'],
		source: '5.jpg',
	},
	{
		id: '314-55-1783',
		author: 'amogus',
		title: 'Raccoon',
		description: 'Ipsum et similique corrupti quas aspernatur tempora voluptates.',
		categories: ['raccoons', 'funny'],
		source: '14.jpg',
	},
	{
		id: '241-12-0856',
		author: 'blablabla392_2008',
		title: 'Dog',
		description: 'Reprehenderit harum voluptatem velit qui.',
		categories: ['dogs'],
		source: '10.jpg',
	},
	{
		id: '758-65-4488',
		author: 'kirill_1021',
		title: 'Cat',
		description: 'Nulla totam eius rerum. Nulla totam eius rerum.',
		categories: ['cats', 'funny'],
		source: '1.jpg',
	},
	{
		id: '377-28-8105',
		author: 'jojo_master',
		title: 'Dog',
		description: 'Consequatur nihil voluptates aut. Tempore architecto omnis occaecati. Provident aut deserunt nesciunt voluptas ut ex. Est ea saepe animi blanditiis soluta nesciunt. Voluptas facere ducimus sunt ab cum placeat temporibus.',
		categories: ['dogs', 'funny'],
		source: '7.jpg',
	},
	{
		id: '597-96-3426',
		author: 'kirill_1021',
		title: 'Raccoon',
		description: 'Laborum repellendus rerum non.',
		categories: ['raccoons', 'funny'],
		source: '11.jpg',
	},
	{
		id: '466-97-31258',
		author: 'user91940913',
		title: 'Cat',
		description: 'Fuga neque vel voluptas quidem voluptatem eum. Quia iure laborum. Voluptas voluptas illum dolorum. Iste consequuntur nulla dignissimos tempora quibusdam.',
		categories: ['cats', 'funny', 'music'],
		source: '3.jpg',
	},
	{
		id: '198-47-004383',
		author: 'user91940913',
		title: 'Dog',
		description: 'Ipsam sequi commodi est ipsum dolorem doloremque. Magni voluptatem est. Temporibus nesciunt est deserunt enim culpa. Molestiae illum corrupti sunt quam optio explicabo deserunt. Adipisci voluptatum necessitatibus quis similique.',
		categories: ['dogs', 'funny'],
		source: '8.jpg',
	},
	{
		id: '396-88-714425',
		author: 'jojo_master',
		title: 'Raccoon',
		description: 'Vel quos omnis et impedit porro eveniet ut. Molestiae eos nulla doloribus. Dolorem et accusantium quisquam.',
		categories: ['raccoons', 'funny'],
		source: '12.jpg',
	},
	{
		id: '769-64-31142',
		author: 'blablabla392_2008',
		title: 'Raccoon',
		description: 'Sequi rem amet tempora. Voluptatem fuga totam beatae eos nesciunt. Iste sit eligendi ipsum voluptatem. Iusto quis assumenda debitis voluptas asperiores nulla. At libero dolorem enim voluptate illo.',
		categories: ['raccoons'],
		source: '15.jpg',
	},
	{
		id: '315-68-841259',
		author: 'user91940913',
		title: 'Raccoon',
		description: 'Et impedit sunt culpa asperiores. Nisi inventore qui qui voluptatibus. In numquam id. Possimus aut eum dolore sequi quaerat nihil.',
		categories: ['raccoons', 'funny'],
		source: '13.jpg',
	},
	{
		id: '836-72-154727',
		author: 'amogus',
		title: 'Cat',
		description: 'Ea omnis non similique. Minima sit et maiores accusantium. Ab voluptate libero sed a est dolorem pariatur.',
		categories: ['cats', 'funny'],
		source: '4.jpg',
	},
	{
		id: '780-61-81963',
		author: 'kirill_1021',
		title: 'Dog',
		description: 'Dicta minima tempora recusandae. Corrupti et nostrum ipsa est et. Aut ex et aut unde. Fuga accusantium asperiores velit. Non amet natus quam.',
		categories: ['dogs', 'funny'],
		source: '6.jpg',
	},
	{
		id: '713-91-745192',
		author: 'jojo_master',
		title: 'Cat',
		description: 'Accusantium eum occaecati qui ut eius. Ut quidem voluptas consequatur natus et. Architecto et non minima tenetur est omnis. Et maiores voluptatibus aut consequatur. Quis est pariatur aut suscipit sed distinctio.',
		categories: ['cats', 'funny'],
		source: '2.jpg',
	},
	{
		id: '815-47-67581',
		author: 'amogus',
		title: 'Dog',
		description: 'Consequatur deleniti accusamus nobis ab qui beatae occaecati.',
		categories: ['dogs', 'funny'],
		source: '9.jpg',
	},
	{
		id: '465-11-133224',
		author: 'blablabla392_2008',
		title: 'Cat',
		description: 'Omnis iusto sit eum minima dolore. Qui ad aut ut quasi. Temporibus voluptatem ut eaque maiores dolores. Repellat iste animi molestiae voluptatem. Iusto libero eos ad ex.',
		categories: ['cats'],
		source: '5.jpg',
	},
	{
		id: '314-55-113783',
		author: 'amogus',
		title: 'Raccoon',
		description: 'Ipsum et similique corrupti quas aspernatur tempora voluptates.',
		categories: ['raccoons', 'funny'],
		source: '14.jpg',
	},
	{
		id: '241-12-053856',
		author: 'blablabla392_2008',
		title: 'Dog',
		description: 'Reprehenderit harum voluptatem velit qui.',
		categories: ['dogs'],
		source: '10.jpg',
	},
];
